from singer_sdk import typing as th

schema = th.PropertiesList(
    th.Property("color", th.StringType),
    th.Property("deleted", th.BooleanType),
    th.Property("has_2fa", th.BooleanType),
    th.Property("id", th.StringType, required=True),
    th.Property("is_admin", th.BooleanType),
    th.Property("is_app_user", th.BooleanType),
    th.Property("is_bot", th.BooleanType),
    th.Property("is_email_confirmed", th.BooleanType),
    th.Property("is_owner", th.BooleanType),
    th.Property("is_primary_owner", th.BooleanType),
    th.Property("is_restricted", th.BooleanType),
    th.Property("is_ultra_restricted", th.BooleanType),
    th.Property("name", th.StringType),
    th.Property(
        "profile",
        th.ObjectType(
            th.Property("avatar_hash", th.StringType),
            th.Property("display_name", th.StringType),
            th.Property("display_name_normalized", th.StringType),
            th.Property("email", th.StringType),
            th.Property("image_24", th.StringType),
            th.Property("image_32", th.StringType),
            th.Property("image_48", th.StringType),
            th.Property("image_72", th.StringType),
            th.Property("image_192", th.StringType),
            th.Property("image_512", th.StringType),
            th.Property("real_name", th.StringType),
            th.Property("real_name_normalized", th.StringType),
            th.Property("status_emoji", th.StringType),
            th.Property("status_text", th.StringType),
            th.Property("team", th.StringType),
        ),
    ),
    th.Property("real_name", th.StringType),
    th.Property("team_id", th.StringType),
    th.Property("tz", th.StringType),
    th.Property("tz_label", th.StringType),
    th.Property("tz_offset", th.IntegerType),
    th.Property("updated", th.NumberType),
    th.Property("who_can_share_contact_card", th.StringType),
).to_dict()
